# Change these first
owner: pixifydigitalagency # Your GitHub username
repo: monitors # Your GitHub repository name

# Add your sites here
sites:
  - name: Corporate Website
    url: https://www.pixify.co.uk/
  - name: Edge Platform
    url: https://edge.pixify.co.uk/
  - name: Senditure Email Marketing
    url: https://www.senditure.co.uk/

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  # cname: demo.upptime.js.org
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /monitors
  logoUrl: https://www.pixify.co.uk/wp-content/uploads/2020/01/favicon-1.png
  name: Public Status Monitors
  introTitle: "**Status Monitor** is our public uptime monitor and status page with real-time updates on all Pixify components."
  introMessage: It's always a good idea to check this page in the event we're experiencing any downtime or upcoming scheduled maintenance.
  navbar:
    - title: Status
      href: /
    - title: Website
      href: https://www.pixify.co.uk/

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
